export const operationContracts = {
  'health.readiness': { actor: 'public', resources: [] },
  'admin.acceptInvitation': { actor: 'public', resources: ['database'] },
  'admin.assignQuestionSet': { actor: 'admin', resources: ['database', 'notification'] },
  'admin.deleteProfileFieldDef': { actor: 'admin', resources: ['database'] },
  'admin.getClientDetail': { actor: 'admin', resources: ['database'] },
  'admin.getClients': { actor: 'admin', resources: ['database'] },
  'admin.getInvitationByToken': { actor: 'public', resources: ['database'] },
  'admin.getInvitations': { actor: 'admin', resources: ['database'] },
  'admin.getProfileFieldDefs': { actor: 'admin', resources: ['database'] },
  'admin.inviteClient': { actor: 'admin', resources: ['database', 'notification'] },
  'admin.removeAssignment': { actor: 'admin', resources: ['database'] },
  'admin.resendInvitation': { actor: 'admin', resources: ['database', 'notification'] },
  'admin.revokeInvitation': { actor: 'admin', resources: ['database'] },
  'admin.saveProfileFieldDef': { actor: 'admin', resources: ['database'] },
  'auth.getClientSession': { actor: 'client', resources: ['database'] },
  'auth.logoutClient': { actor: 'client', resources: ['database'] },
  'client.getMyAssignments': { actor: 'client', resources: ['database'] },
  'client.getOnboardingFields': { actor: 'client', resources: ['database'] },
  'client.saveClientProfile': { actor: 'client', resources: ['database'] },
  'client.submitAssignment': { actor: 'client', resources: ['database', 'notification'] },
  'clients.loginClient': { actor: 'public', resources: ['database'] },
  'clients.registerClient': { actor: 'public', resources: ['database'] },
  'declarations.getDeclarationById': { actor: 'client', resources: ['database'] },
  'declarations.getDeclarations': { actor: 'admin', resources: ['database'] },
  'declarations.getEvidenceFileAccess': { actor: 'client', resources: ['database', 'storage'] },
  'declarations.submitDeclaration': { actor: 'client', resources: ['database'] },
  'declarations.submitDeclarationWithAnswers': { actor: 'client', resources: ['database', 'notification'] },
  'declarations.submitFeedback': { actor: 'admin', resources: ['database', 'notification'] },
  'declarations.uploadDeclarationFile': { actor: 'client', resources: ['database', 'storage'] },
  'questions.deleteQuestion': { actor: 'admin', resources: ['database'] },
  'questions.deleteQuestionSet': { actor: 'admin', resources: ['database'] },
  'questions.getQuestionSet': { actor: 'admin', resources: ['database'] },
  'questions.getQuestionSets': { actor: 'admin', resources: ['database'] },
  'questions.getQuestionsForType': { actor: 'client', resources: ['database'] },
  'questions.reorderQuestions': { actor: 'admin', resources: ['database'] },
  'questions.saveQuestion': { actor: 'admin', resources: ['database'] },
  'questions.saveQuestionSet': { actor: 'admin', resources: ['database'] },
}

export const resourceEnv = {
  database: ['DATABASE_URL'],
  notification: ['PORTAL_NOTIFICATION_PROVIDER', 'PORTAL_NOTIFICATION_FROM'],
  storage: ['PORTAL_STORAGE_BUCKET'],
}
